# yaml-language-server: $schema=config-v1.schema.json
version: 1

overlay:
  monitor: 0
  attach: false
  start-hidden: false

tosu:
  url: http://127.0.0.1:24050
  start-with-overlay:
    enabled: true
    privileged: false
    executable: /usr/bin/tosu
    arguments: []
    working-directory: /opt/tosu
    auto-url: false
